### ISSUE TITLE
gobandroid-ai-gnugo should be merged with gobandroid

### ISSUE THREAD

**Issue by echo083** [ligi/gobandroid-ai-gnugo#4]
Hello,

To play with the ia in gobandroid it is necessary to install gobandroid-ai-gnugo with gobandroid. If gobandroid-ai-gnugo was included with gobandroid it would be simple.

Thanks

**Comment by ligi** [comment]
I like the modular aspect and will not bundle the AI to gobandroid. Perhaps I can make a bundled version as an extra thing - but the core will be AI free ( I do not really like playing vs AI and do not want my space wasted with it ;)

**Comment by echo083** [comment]
Ok you have a good point about the memory waste so I won't ask again for this functionality.

I made a request on f-droid forum to include gobandroid-ai-gnugo in their repo as gobandroid is already available and not gnugo :
https://f-droid.org/forums/topic/gobandroid-and-gnugo/

Thanks

**Comment by Asara** [comment]
Didn't want to open a new issue so I'll just comment here.  Is there any plan to add this to F-Droid?  Or is compiling it the recommended route for those of us who don't have the Play Store?

Thanks!

**Comment by ligi** [comment]
In the case of FDroid Gobandroid should redirect you to the download of the apk from github

**Comment by Asara** [comment]
For the gnugo ai?

**Comment by ligi** [comment]
ya - it should fall back to this: ./main/java/org/ligi/gobandroid_hd/etc/GobandroidConfiguration.java:    public static final String GNUGO_MANUAL_INSTALL_URL = "http://github.com/downloads/ligi/gobandroid-ai-gnugo/org_ligi_gobandroid_ai_gnugo_0.7.apk";
